In [68]:
import pandas as pd
from pathlib import Path
# import s3fs
# fs = s3fs.FileSystem()

NameError: name 's3fs' is not defined

In [86]:
data_dir = "/Users/oholm/annad/ordtidni/Gigaword/output/fjardarpostur/"
data_dir = "/Users/oholm/annad/ordtidni/Gigaword/output/andriki/"
p = Path(data_dir).glob('**/*')
files = [x for x in p if x.is_file()]
files = [file for file in files if str(file).endswith('.parquet')]
files

[PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2013/part-00000-950dc856-f9e1-4a77-a965-6f36d64dc287-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2014/part-00000-e3a02997-f5bc-4532-81ba-cc951540638b-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2015/part-00000-ff3f4129-4582-44a6-b855-fd7e128549e7-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2012/part-00000-0d147481-ddb2-4301-9657-23f8704ca3d4-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2008/part-00000-99e2cd5e-36d4-4103-94d5-ce825c16ebc2-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2001/part-00000-b8ee1201-d57e-4e0d-beac-c8bee07fe70d-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2006/part-00000-87e891f4-037c-4e2c-af3d-c962f0110900-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2007/part-00000-df77fa70-5fff-42e7-8827-e9411489257e-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2000/part-00000-5873fe2a-000e-4e8c-b441-a55272e30ee8-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2009/part-00000-c455ae3f-829c-4b8b-a29d-155484959899-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2017/part-00000-bcbbf6aa-7753-4232-8643-da8f0e6e3004-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2010/part-00000-15690caa-f1a6-48db-9726-a5f621a1a0c8-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2011/part-00000-91cf58cc-6c5b-4543-aaba-71d68223e4c8-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2016/part-00000-c7f63e3f-2ece-4be9-acc6-ea2777b7aa7f-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/1997/part-00000-b109a481-b664-4aea-b586-091926b17a18-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/1999/part-00000-5f04a743-e69f-488e-8523-e30594d30539-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/1998/part-00000-72e75ad8-d59b-4c56-92e6-aa3ed10ef978-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2005/part-00000-7f05e254-6f6e-4f1a-a0ee-d2d734900a41-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2002/part-00000-481d932e-ab5c-414d-85e1-66eac5af779a-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2003/part-00000-424334c7-77ce-42e6-9037-9a3db7cd6b5b-c000.snappy.parquet'),
 PosixPath('/Users/oholm/annad/ordtidni/Gigaword/output/andriki/2004/part-00000-74b18c7f-6b1f-46b9-9d25-202dae4a178b-c000.snappy.parquet')]

In [87]:
word_occurance_count = pd.DataFrame({'occurance_count':[0]},index=['barn']) # starting dataframe
# display(word_occurance_count)
print('----'*8, 'start iteration', '----'*8)
for file in files:
    corpus_doc = pd.read_parquet(file)
#     print('read in dataframe')
#     display(corpus_doc.head(2))
    noun_mask = corpus_doc['POS'].str.startswith('n')
#     print('there are', sum(noun_mask), 'nouns in the set')
    nouns_only_df = corpus_doc[noun_mask]
#     print('nouns only')
#     display(nouns_only_df.sample(3))
#     all_nouns_list = nouns_only_df['Lemma'].unique()
    noun_occurrence_count =\
        nouns_only_df[['Lemma', 'POS']]\
        .groupby(by='Lemma')\
        .count()\
        ['POS']\
        .rename('additions')\
        
#     print('there are',
#           len(noun_occurrence_count),
#           'noun lemmas')
    word_occurance_count = pd.concat([word_occurance_count, noun_occurrence_count], axis=1).fillna(0)
    word_occurance_count['occurance_count'] = word_occurance_count['occurance_count'] + word_occurance_count['additions']
    word_occurance_count.drop('additions', axis=1,inplace=True)
#     display(word_occurance_count.head(3))

-------------------------------- start iteration --------------------------------

In [90]:
word_occurance_count.sort_values(by='occurance_count', ascending=False).head(60).reset_index()

                 index  occurance_count
0                maður          16580.0
1                   ár          12782.0
2                  mál           7764.0
3                 ríki           6913.0
4                 fólk           6041.0
5                 land           5871.0
6                vegur           5860.0
7               Ísland           5249.0
8                dagur           5125.0
9              flokkur           4438.0
10                 lag           4236.0
11               króna           3560.0
12           fyrirtæki           3531.0
13      Vefþjóðviljinn           3450.0
14                dæmi           3407.0
15              staður           3217.0
16           þingmaður           3155.0
17             skattur           3101.0
18          Samfylking           3066.0
19         ríkisstjórn           3012.0
20                tími           2946.0
21               grein           2571.0
22               frétt           2569.0
23                 orð           2479.0
24          fjölmiðill           2327.0
25             kosning           2285.0
26              ástæða           2261.0
27                 bók           2242.0
28                leið           2230.0
29         Íslendingur           2220.0
30              háttur           2189.0
31     stjórnmálamaður           2180.0
32              skoðun           2126.0
33              kostur           2106.0
34  Sjálfstæðisflokkur           2082.0
35            formaður           2050.0
36         fréttamaður           1934.0
37             milljón           1921.0
38               regla           1914.0
39       Evrópusamband           1884.0
40      skattgreiðandi           1884.0
41          Morgunblað           1869.0
42              umræða           1847.0
43                þjóð           1846.0
44                kona           1831.0
45            ráðherra           1819.0
46           Reykjavík           1813.0
47             forseti           1806.0
48               banki           1760.0
49               starf           1751.0
50                blað           1735.0
51          niðurstaða           1698.0
52                raun           1692.0
53              þáttur           1671.0
54             Alþingi           1645.0
55         starfsmaður           1637.0
56               áhrif           1619.0
57                sinn           1619.0
58         Ríkisútvarp           1612.0
59               hluti           1605.0

In [4]:
test_file_df = pd.read_parquet("/Users/oholm/annad/ordtidni/Gigaword/output/fjardarpostur/2017/part-00000-c6e286ed-ec32-49d3-b155-0819d189b398-c000.snappy.parquet")

In [7]:
test_file_df.head()
test_file_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97614 entries, 0 to 97613
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   input_file   97614 non-null  object
 1   Paragraph    97614 non-null  int64
 2   Sentence     97614 non-null  int64
 3   word_number  97614 non-null  int32
 4   Lemma        97614 non-null  object
 5   POS          97614 non-null  object
 6   Word         97614 non-null  object
dtypes: int32(1), int64(2), object(4)
memory usage: 4.8+ MB

In [11]:
lemmas = ['hundur', 'barn']

In [41]:
noun_pos_uniq = [pos for pos in test_file_df['POS'].unique() if pos.startswith('n')]

In [19]:
noun_mask = test_file_df['POS'].str.startswith('n')
print('there are', sum(noun_mask), 'nouns in the set')

there are 29674 nouns in the set

In [40]:
nouns_only_df = test_file_df[noun_mask]
display(nouns_only_df.sample(8))
all_nouns_list = nouns_only_df['Lemma'].unique()

,input_file,Paragraph,Sentence,word_number,Lemma,POS,Word
57216,11/G-44-6294086.xml,2,5,4,Hlöðver,nken-s,Hlöðver
18304,11/G-44-6294119.xml,27,1,19,jól,nhfþ,jólum
70320,11/G-44-6294082.xml,2,4,9,Kristín,nven-s,Kristín
84260,10/G-44-6182973.xml,3,6,8,mætingarskylda,nven,mætingarskylda
56208,03/G-44-6009049.xml,1,4,14,íbúð,nveo,íbúð
37594,10/G-44-6208372.xml,1,2,9,heildstæða,nvfþ,heildstæðum
37101,08/G-44-6009165.xml,14,1,29,hjú,nhfþ,hjúum
47762,09/G-44-6013334.xml,1,3,1,markmið,nhen,Markmið

In [63]:
noun_occurrence_count =\
    nouns_only_df[['Lemma', 'POS']]\
    .groupby(by='Lemma')\
    .count()\
    ['POS']\
    .rename('occurance_count')
print('there are',
      len(noun_occurrence_count),
      'noun lemmas')

top10_nouns =\
    noun_occurrence_count\
    .sort_values(ascending=False)\
    .head(10)
display(top10_nouns)

there are 7843 noun lemmas

Lemma
ár                  651
Hafnarfjörður       450
fólk                237
dagur               226
barn                220
mynd                173
Hafnarfjarðarbær    156
bær                 150
króna               148
maður               143
Name: occurance_count, dtype: int64

In [67]:
temp_series =\
    noun_occurrence_count\
    .rename('additions')
mump_df = pd.concat([noun_occurrence_count, temp_series], axis=1)
mump_df['occurance_count'] = mump_df['occurance_count'] + mump_df['additions']
mump_df.drop('additions', axis=1)

         occurance_count
Lemma
-Afnemi                2
-Dreg                  2
-fóta                  2
-skóli                 4
-sýning                2
...                  ...
þúsund                12
þýðing                 4
”                     16
…                     30
⅔                      2

[7843 rows x 1 columns]

In [39]:
most_common_nouns.name = 'top_nouns'

In [ ]:
noun_filter = nouns_only_df

In [54]:
temp_series = noun_occurrence_count['POS']
temp_series

Lemma
-Afnemi     1
-Dreg       1
-fóta       1
-skóli      2
-sýning     1
           ..
þúsund      6
þýðing      2
”           8
…          15
⅔           1
Name: POS, Length: 7843, dtype: int64

In [ ]:
for noun in most_common_nouns:

In [45]:
noun_occurrence_count.index

Index(['-Afnemi', '-Dreg', '-fóta', '-skóli', '-sýning', '0.5ltrvatn',
       '1,5dldöðla', '1-4.bekkur', '1/2sítróni', '10.október',
       ...
       'þétting', 'þöggun', 'þökk', 'þöll', 'þörf', 'þúsund', 'þýðing', '”',
       '…', '⅔'],
      dtype='object', name='Lemma', length=7843)

In [53]:
s1 = pd.Series([1, 2], index=['A', 'B'], name='s1')
s2 = pd.Series([3, 4], index=['A', 'C'], name='s2')
pd.concat([s1, s2], axis=1)

    s1   s2
A  1.0  3.0
B  2.0  NaN
C  NaN  4.0